= Project Overview

In this project, you will redesign an app to follow the Material Design guidelines and translate a set of static design mocks to a living and breathing app.

= Why this Project?

This project gives you an opportunity to improve an app’s design, a vital skill for building apps users will love. It also replicates a common developer task of updating and changing an app's design as new standards are released.

= Make Your App Material

This repository stores the starter code for the XYZ Reader project in Udacity's Android Nanodegree.

Transformed the user experience of a news reading app using Material Design principles. This includes consistent and meaningful use of Material Design UI components, fonts, color, motion and surfaces.

= What Will I Learn

- Understand the fundamentals of Android design.
- Apply Material Design guidelines to an mobile application.
- Separate an interface into surfaces.
- Effectively use transitions and motion.

= Srceenshots

https://user-images.githubusercontent.com/7755518/39406642-7a35c178-4bc2-11e8-90de-db73fa7da293.png

https://user-images.githubusercontent.com/7755518/39406643-7c3314c6-4bc2-11e8-9b5c-8f3cf9578b13.png
